const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
const SAVE_TASK_SUCCESS = 'SAVE_TASK_SUCCESS';
const SET_TASK_STATUS = 'SET_TASK_STATUS';
const RESET_TASKS = 'RESET_TASKS';

export default {
	FETCH_TASKS_SUCCESS,
	SET_TASK_STATUS,
	SAVE_TASK_SUCCESS,
	RESET_TASKS
};
